### ISSUE TITLE
Random Bugs I noticed

### ISSUE THREAD

**Issue by Mr-Sir-XXIII-Esq** [DrNewbie/RNGModifier#81]
I will add to this/make a new post as I find more issues.
Hotline day 1: the cars having money in them isn't consistent. Sometimes only 1 car has money.
The Force max basement loot definitely doesn't work.  It seems to always spawn 2 weapons and no coke.
Cook off: flare location doesn't work. Does it conflict with other settings maybe?

While I'm here I'd like to request the force max loot option to be added to every applicable heist

**Comment by Berk-Rider** [comment]
I forgot to add "wip" to the hotline miami options names
in cook off the flare should work but only for the first time I assume, this ain't an option I created plus I never enabled it in my game
force max loot in all heists is planned but will take some time since not all of them work the same way as the already added ones
